CREATE TABLE Commit (
    CmtID VARCHAR(40) PRIMARY KEY,
    CmtMensagem TEXT NOT NULL,
    NoArqAlterados INT NOT NULL,
    NoAdicoes INT NOT NULL,
    NoRemocoes INT NOT NULL,
    DataCommit TIMESTAMP NOT NULL,
    FeitoPorUsrID VARCHAR(30) NOT NULL,
    BchID VARCHAR(11) NOT NULL,
    FOREIGN KEY (FeitoPorUsrID) REFERENCES Usuário(UsrID),
    FOREIGN KEY (BchID) REFERENCES Branch(BchID)
);

CREATE TABLE CmtAlteraPst(
    PstID VARCHAR(11) NOT NULL,
    CmtID VARCHAR(40) NOT NULL,
    PRIMARY KEY (PstID, CmtID),
    FOREIGN KEY (PstID) REFERENCES Pasta(PstID),
    FOREIGN KEY (CmtID) REFERENCES Commit(CmtID)
);

CREATE TABLE CmtAlteraArq(
    CmtID VARCHAR(40) NOT NULL,
    ArqID VARCHAR(7) NOT NULL,
    AlteracoesTexto TEXT NOT NULL,
    PRIMARY KEY (CmtID, ArqID),
    FOREIGN KEY (CmtID) REFERENCES Commit(CmtID),
    FOREIGN KEY (ArqID) REFERENCES Arquivo(ArqID)
);

